# Generated by Django 5.2.9 on 2025-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('selfie_photo', models.ImageField(upload_to='selfies/%Y/%m/%d/', verbose_name='Selfie Photo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
