# Generated by Django 5.2.9 on 2025-12-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_company_checkin_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Personnel Check-In', 'verbose_name_plural': 'Personnel Check-Ins'},
        ),
        migrations.AddField(
            model_name='checkin',
            name='current_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_checkins', to='checkin.company', verbose_name='Current Company Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_checkins', to='checkin.company', verbose_name="Employee's Company"),
        ),
    ]
