# Generated by Django 5.2.9 on 2025-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_checkin_options_checkin_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
