# Generated by Django 5.2.9 on 2025-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_alter_checkin_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
