# Generated by Django 6.0 on 2025-12-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
