# Generated by Django 6.0 on 2025-12-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0002_payment_amount_received_payment_change_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True, verbose_name='Room No.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Occupied', 'Occupied')], default='Available', max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Bed Spacer', 'Bed Spacer')], max_length=20, verbose_name='Room Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Room Price')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room No. (Legacy)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Payment_Scheduler.room'),
        ),
    ]
