# Generated by Django 6.0 on 2025-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0003_room_alter_customer_room_no_customer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
