# Generated by Django 6.0 on 2025-12-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0005_room_capacity_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
