# Generated by Django 6.0 on 2025-12-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0006_room_date_left_alter_room_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
