# Generated by Django 6.0 on 2025-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0007_customer_date_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Non-Student', 'Non-Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
