# Generated by Django 5.2.8 on 2025-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0008_remove_customer_room_no_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouseuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
