# Generated by Django 6.0 on 2025-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0009_alter_boardinghouseuser_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardinghouseuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
