# Generated by Django 6.0 on 2025-12-18 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0010_customer_date_entry_alter_boardinghouseuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_entry',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
