# Generated by Django 6.0 on 2025-12-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0011_alter_customer_date_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='parents_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='parents_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
