# Generated by Django 6.0 on 2025-12-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0012_remove_customer_age_remove_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_from_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_to_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='Payment_Scheduler.customer')),
                ('room_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='Payment_Scheduler.room')),
                ('room_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='Payment_Scheduler.room')),
            ],
        ),
    ]
