# Generated by Django 6.0 on 2026-01-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Scheduler', '0013_roomtransferhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
