# Generated by Django 5.2.8 on 2025-12-12 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_tin', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_description', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Piece'), ('BOX', 'Box'), ('PKG', 'Package'), ('KG', 'Kilogram'), ('LTR', 'Liter'), ('MTR', 'Meter')], max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_description'],
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('document_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_tin', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='POS.customer')),
            ],
            options={
                'ordering': ['-transaction_date', '-transaction_no'],
            },
        ),
        migrations.CreateModel(
            name='POSLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POS.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.postransaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
