# Generated by Django 5.2.8 on 2025-12-12 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_customer_item_postransaction_poslineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_entry', 'customer_name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('WALKIN', 'Walk-in'), ('REGULAR', 'Regular'), ('SUPPLIER', 'Supplier')], default='WALKIN', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
