# Generated by Django 5.2.8 on 2025-12-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_alter_customer_options_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postransaction',
            name='customer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.customer'),
        ),
    ]
