# Generated by Django 6.0 on 2025-12-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_remove_item_created_by_remove_item_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='bank_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='cash_amount_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='cash_amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='check_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('PO', 'PO'), ('CHECK', 'Check'), ('ONLINE', 'Online Transfer')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='online_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
