# Generated by Django 5.2.8 on 2025-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(help_text='Official title certificate number', max_length=50, unique=True, verbose_name='Title Number')),
                ('lot_no', models.CharField(help_text='Lot identification number', max_length=100, verbose_name='Lot Number')),
                ('lot_area', models.DecimalField(decimal_places=2, default=0.0, help_text='Total area in square meters', max_digits=10, verbose_name='Lot Area (sqm)')),
                ('title_classification', models.CharField(choices=[('RES', 'RESIDENTIAL'), ('COM', 'COMMERCIAL'), ('IND', 'INDUSTRIAL'), ('AGR', 'AGRICULTURAL')], default='RES', max_length=3, verbose_name='Classification')),
                ('title_status', models.CharField(choices=[('ACT', 'ACTIVE'), ('PND', 'PENDING'), ('SOLD', 'SOLD'), ('ARC', 'ARCHIVED')], default='ACT', max_length=4, verbose_name='Status')),
                ('title_description', models.TextField(blank=True, help_text='Optional property description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
