# Generated by Django 5.2.8 on 2025-12-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0002_alter_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Date the title movement/transfer was officially executed.', verbose_name='Transaction Date')),
                ('new_owner_name', models.CharField(max_length=255, verbose_name='New Owner/Party')),
                ('movement_type', models.CharField(max_length=50, verbose_name='Movement Type')),
                ('document_ref_no', models.CharField(max_length=100, unique=True, verbose_name='Document Reference No.')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Remarks')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_movements', to='RDRealty_App.property', verbose_name='Associated Property')),
            ],
            options={
                'verbose_name': 'Title Movement',
                'verbose_name_plural': 'Title Movements',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(help_text='The year the tax assessment applies to (e.g., 2025).', verbose_name='Tax Year')),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Assessed Value')),
                ('tax_amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount Due')),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('DUE', 'Due'), ('OVDR', 'Overdue'), ('EXMPT', 'Exempt')], default='DUE', max_length=5, verbose_name='Payment Status')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='RDRealty_App.property', verbose_name='Associated Property')),
            ],
            options={
                'verbose_name': 'Property Tax Record',
                'verbose_name_plural': 'Property Tax Records',
                'unique_together': {('property', 'tax_year')},
            },
        ),
    ]
