# Generated by Django 5.2.8 on 2025-12-09 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0003_titlemovement_propertytax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytax',
            old_name='property',
            new_name='associated_property',
        ),
        migrations.AlterUniqueTogether(
            name='propertytax',
            unique_together={('associated_property', 'tax_year')},
        ),
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='propertytax',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
    ]
