# Generated by Django 5.2.8 on 2025-12-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0004_rename_property_propertytax_associated_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlemovement',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyTax',
        ),
        migrations.DeleteModel(
            name='TitleMovement',
        ),
    ]
