# Generated by Django 6.0 on 2025-12-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0006_usermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OwnerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_specific', models.TextField(blank=True, null=True)),
                ('loc_province', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_city', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='RDRealty_App.property', to_field='property_id')),
            ],
            options={
                'db_table': 'rdrealty_owner_information',
            },
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
