# Generated by Django 5.2.8 on 2025-12-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0007_property_property_id_property_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title_classification',
            field=models.CharField(choices=[('RES', 'RESIDENTIAL'), ('COM', 'COMMERCIAL'), ('IND', 'INDUSTRIAL'), ('AGR', 'AGRICULTURAL'), ('MIX', 'MIXED USE'), ('INS', 'INSTITUTIONAL')], default='RES', max_length=3, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('COL', 'COLLATERAL'), ('SOLD', 'SOLD'), ('UND', 'UNDER DEVELOPMENT'), ('FORC', 'FORECLOSED'), ('DISP', 'DISPOSED'), ('PENT', 'PENDING TRANSFER'), ('INT', 'INACTIVE')], default='ACT', max_length=4, verbose_name='Status'),
        ),
    ]
