# Generated by Django 6.0 on 2025-12-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0008_alter_property_title_classification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerInformation',
            new_name='LocalInformation',
        ),
        migrations.AlterModelTable(
            name='localinformation',
            table='rdrealty_local_information',
        ),
    ]
