# Generated by Django 6.0 on 2025-12-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0009_rename_ownerinformation_localinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_fullname', models.CharField(blank=True, max_length=80, null=True)),
                ('oi_bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('oi_custody_title', models.CharField(blank=True, max_length=60, null=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='RDRealty_App.property', to_field='property_id')),
            ],
            options={
                'db_table': 'rdrealty_owner_information',
            },
        ),
    ]
