# Generated by Django 6.0 on 2025-12-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0010_ownerinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi_encumbrance', models.CharField(blank=True, max_length=250, null=True)),
                ('fi_mortgage', models.CharField(blank=True, max_length=150, null=True)),
                ('fi_borrower', models.CharField(blank=True, max_length=80, null=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='RDRealty_App.property', to_field='property_id')),
            ],
            options={
                'db_table': 'rdrealty_financial_information',
            },
        ),
    ]
