# Generated by Django 6.0 on 2025-12-25 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinformation',
            name='loc_barangay',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localinformation',
            name='loc_city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localinformation',
            name='loc_province',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ownerinformation',
            name='oi_fullname',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_classification',
            field=models.CharField(choices=[('RES', 'RESIDENTIAL'), ('COM', 'COMMERCIAL'), ('IND', 'INDUSTRIAL'), ('AGR', 'AGRICULTURAL'), ('MIX', 'MIXED USE'), ('INS', 'INSTITUTIONAL')], db_index=True, default='RES', max_length=3, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('COL', 'COLLATERAL'), ('SOLD', 'SOLD'), ('UND', 'UNDER DEVELOPMENT'), ('FORC', 'FORECLOSED'), ('DISP', 'DISPOSED'), ('PENT', 'PENDING TRANSFER'), ('INT', 'INACTIVE')], db_index=True, default='ACT', max_length=4, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='localinformation',
            index=models.Index(fields=['loc_province', 'loc_city', 'loc_barangay'], name='rdrealty_lo_loc_pro_7a2575_idx'),
        ),
    ]
