# Generated by Django 6.0 on 2025-12-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0015_alter_localinformation_loc_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(verbose_name='Tax Year')),
                ('tax_quarter', models.CharField(max_length=20, verbose_name='Quarter')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('tax_due_date', models.DateField(verbose_name='Due Date')),
                ('tax_from', models.DateField(verbose_name='Period From')),
                ('tax_to', models.DateField(verbose_name='Period To')),
                ('tax_status', models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Overdue', 'Overdue'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Contested', 'Contested'), ('Exempted', 'Exempted'), ('Waived', 'Waived')], default='Pending', max_length=20, verbose_name='Status')),
                ('tax_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='RDRealty_App.property', to_field='property_id')),
            ],
            options={
                'db_table': 'rdrealty_tax_record',
            },
        ),
    ]
