# Generated by Django 6.0 on 2026-01-03 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0017_alter_property_options_alter_notification_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airequestlog',
            options={'verbose_name': 'AI Request Log', 'verbose_name_plural': 'AI Request Logs'},
        ),
        migrations.CreateModel(
            name='TitleMovementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_purpose', models.CharField(max_length=200, verbose_name='Purpose of Release')),
                ('tm_transmittal_no', models.CharField(max_length=20, verbose_name='Transmittal Number')),
                ('tm_received_by', models.CharField(max_length=60, verbose_name='Received By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='title_movements', to='RDRealty_App.property', to_field='property_id')),
                ('tm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('tm_released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_movements', to=settings.AUTH_USER_MODEL, verbose_name='Released By')),
            ],
            options={
                'db_table': 'rdrealty_title_mov_request',
            },
        ),
    ]
