# Generated by Django 6.0 on 2026-01-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0018_alter_airequestlog_options_titlemovementrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleMovementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='movement_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='RDRealty_App.titlemovementrequest')),
            ],
            options={
                'db_table': 'rdrealty_title_mov_docs',
            },
        ),
    ]
