# Generated by Django 6.0 on 2026-01-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0019_titlemovementdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemovementrequest',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titlemovementrequest',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('Returned', 'Returned')], default='Released', max_length=20),
        ),
    ]
