# Generated by Django 6.0 on 2026-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0020_titlemovementrequest_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='titlemovementrequest',
            name='tm_turned_over_by',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Turned Over By'),
        ),
        migrations.AlterField(
            model_name='titlemovementrequest',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned')], default='Released', max_length=20),
        ),
    ]
