# Generated by Django 6.0 on 2026-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0022_propertytax_created_at_propertytax_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemovementrequest',
            name='tm_received_by_on_return',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Received By (On Return)'),
        ),
        migrations.AddField(
            model_name='titlemovementrequest',
            name='tm_returned_by',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Returned By'),
        ),
    ]
