# Generated by Django 6.0 on 2026-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0023_titlemovementrequest_tm_received_by_on_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovementrequest',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned'), ('Lost', 'Lost')], default='Released', max_length=20),
        ),
    ]
