# Generated by Django 6.0 on 2026-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0024_alter_titlemovementrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovementrequest',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned'), ('Lost', 'Lost'), ('Pending Return', 'Pending Return')], default='Released', max_length=20),
        ),
    ]
