# Generated by Django 6.0 on 2026-01-03 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0025_alter_titlemovementrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PROPERTY', 'Property'), ('USER', 'User'), ('TAX', 'Tax Record'), ('MOVEMENT', 'Title Movement')], max_length=20),
        ),
    ]
