# Generated by Django 6.0 on 2026-01-04 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0027_notification_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('UPDATE', 'Update'), ('STATUS_CHANGE', 'Status Change'), ('TAX_UPDATE', 'Tax Update'), ('MOVEMENT_UPDATE', 'Movement Update')], default='UPDATE', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='RDRealty_App.property', to_field='property_id')),
            ],
            options={
                'db_table': 'rdrealty_property_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
