# Generated by Django 6.0 on 2026-01-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDRealty_App', '0028_propertyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyhistory',
            name='change_type',
            field=models.CharField(choices=[('ADD', 'Add'), ('UPDATE', 'Update'), ('STATUS_CHANGE', 'Status Change'), ('TAX_UPDATE', 'Tax Update'), ('MOVEMENT_UPDATE', 'Movement Update')], default='UPDATE', max_length=20),
        ),
    ]
